"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Mail } from "lucide-react";
import { toast } from "sonner";
import { Aurora } from "@/components/landing/aurora";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/ui/logo";

export default function ForgotPasswordPage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);

    try {
      const response = await fetch("/api/auth/password-reset", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email }),
      });

      const payload = (await response.json().catch(() => ({}))) as { error?: string };

      if (!response.ok) {
        throw new Error(payload.error ?? "Unable to send reset email");
      }

      toast.success("Reset link sent", {
        description: "If the account exists, check your inbox for the reset email.",
      });
      router.push("/login");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Unable to send reset email");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="relative grid min-h-dvh lg:grid-cols-2">
      <div className="relative flex flex-col px-5 py-8 sm:px-10">
        <div className="flex items-center justify-between">
          <Link href="/" className="focus-ring rounded-lg">
            <Logo />
          </Link>
          <Link
            href="/login"
            className="focus-ring inline-flex items-center gap-1.5 rounded-lg px-2 py-1 text-sm text-ink-mute transition-colors hover:text-ink"
          >
            <ArrowLeft className="h-4 w-4" /> Back
          </Link>
        </div>

        <div className="flex flex-1 items-center justify-center">
          <div className="w-full max-w-sm">
            <h1 className="text-3xl font-semibold tracking-tight">Reset your password</h1>
            <p className="mt-2 text-sm text-ink-mute">
              We will send a recovery link to your email. It opens a page where you can set a new
              password.
            </p>

            <form onSubmit={onSubmit} className="mt-7 space-y-4">
              <label className="block">
                <span className="mb-1.5 block text-[0.8rem] font-medium text-ink-soft">Work email</span>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-mute">
                    <Mail className="h-4 w-4" />
                  </span>
                  <input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="you@company.com"
                    autoComplete="email"
                    required
                    className="focus-ring h-12 w-full rounded-xl border border-line bg-surface pl-10 pr-4 text-sm text-ink placeholder:text-ink-faint transition-colors focus:border-accent/50"
                  />
                </div>
              </label>

              <Button type="submit" size="lg" loading={loading} className="group w-full">
                Send reset link
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
              </Button>
            </form>

            <p className="mt-6 text-center text-sm text-ink-mute">
              Remembered it?{" "}
              <Link href="/login" className="focus-ring rounded font-medium text-brand-bright hover:underline">
                Sign in
              </Link>
            </p>
          </div>
        </div>
        <div className="h-6" />
      </div>

      <aside className="relative hidden overflow-hidden border-l border-line bg-base-2 lg:block">
        <Aurora />
        <div className="grid-bg pointer-events-none absolute inset-0 [mask-image:radial-gradient(80%_70%_at_60%_30%,black,transparent)]" />
        <div className="relative flex h-full flex-col justify-center px-14">
          <h2 className="max-w-md text-balance text-4xl font-semibold leading-tight tracking-tight">
            One email. <span className="text-accent">A fresh password.</span>
          </h2>
          <p className="mt-4 max-w-sm text-ink-soft">
            The reset email is generated by the app and delivered through Mailjet. Supabase handles
            the recovery session after the link is opened.
          </p>
        </div>
      </aside>
    </main>
  );
}
