services:
  - type: web
    name: docuextract-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: MISTRAL_API_KEY
        value: demNtE67EC6JgovKPd8dDmOtpUeAseeY
      - key: DATABASE_URL
        value: postgresql://postgres.eopwilbjjnirqxptmiyp:DocuExtract2026!@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - key: SUPABASE_JWT_SECRET
        value: U7JTgombuqGbDKQY83sqEi0FLbTVJsAGvLqrkaxHmvjnCRglIOrikRtkFoSlbe7YSiGUMEqi7CIrd+nzjEyXuA==
