-- Manual Supabase SQL for invoice workflow hardening.
-- Note: Supabase CLI was not available in this workspace, so this file is
-- provided as a manual migration script to apply in the SQL editor or convert
-- into an official migration in your Supabase project.

alter table public.invoices
  add column if not exists processing_started_at timestamptz,
  add column if not exists processed_at timestamptz,
  add column if not exists last_error text,
  add column if not exists retry_count integer not null default 0,
  add column if not exists file_size_bytes bigint,
  add column if not exists mime_type text,
  add column if not exists file_hash text,
  add column if not exists duplicate_of_invoice_id integer references public.invoices(id) on delete set null,
  add column if not exists needs_attention boolean not null default false,
  add column if not exists attention_reasons jsonb not null default '[]'::jsonb,
  add column if not exists reviewed_by text,
  add column if not exists reviewed_at timestamptz;

alter table public.invoices
  drop constraint if exists invoices_status_check;

alter table public.invoices
  add constraint invoices_status_check
  check (status in ('processing', 'review', 'approved', 'rejected', 'failed'));

create index if not exists invoices_user_id_file_hash_idx on public.invoices (user_id, file_hash);
create index if not exists invoices_status_idx on public.invoices (status);

create table if not exists public.invoice_audit_log (
  id bigint generated by default as identity primary key,
  invoice_id integer not null references public.invoices(id) on delete cascade,
  user_id uuid,
  action text not null,
  from_status text,
  to_status text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists invoice_audit_log_invoice_id_idx
  on public.invoice_audit_log (invoice_id, created_at desc);

create table if not exists public.webhook_outbox (
  id bigint generated by default as identity primary key,
  invoice_id integer not null references public.invoices(id) on delete cascade,
  event_type text not null,
  payload jsonb not null,
  delivery_status text not null default 'pending',
  delivery_attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create index if not exists webhook_outbox_delivery_status_idx
  on public.webhook_outbox (delivery_status, created_at asc);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  granted_by uuid references auth.users(id) on delete set null,
  granted_at timestamptz not null default now(),
  note text
);

create index if not exists admin_users_granted_at_idx
  on public.admin_users (granted_at desc);

alter table public.admin_users enable row level security;

drop policy if exists "Service role manages admin users" on public.admin_users;
create policy "Service role manages admin users"
  on public.admin_users
  for all
  to service_role
  using (true)
  with check (true);

alter table public.invoice_audit_log enable row level security;
alter table public.webhook_outbox enable row level security;

drop policy if exists "Users can view their invoice audit log" on public.invoice_audit_log;
create policy "Users can view their invoice audit log"
  on public.invoice_audit_log
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.invoices
      where invoices.id = invoice_audit_log.invoice_id
        and invoices.user_id = auth.uid()::text
    )
  );

drop policy if exists "Service role manages invoice audit log" on public.invoice_audit_log;
create policy "Service role manages invoice audit log"
  on public.invoice_audit_log
  for all
  to service_role
  using (true)
  with check (true);

drop policy if exists "Service role manages webhook outbox" on public.webhook_outbox;
create policy "Service role manages webhook outbox"
  on public.webhook_outbox
  for all
  to service_role
  using (true)
  with check (true);
